version: "3.8"
services:
  expense-tracker-app:
    build: .
    image: ${DOCKER_HUB_CREDS_USR}/ expense-tracker:latest
    container_name: expense-tracker-app
    ports:
    - target: 5000
      published: 80
    ports:
    - target: 5000
      published: 5000