version: "3.8"
services:
  expense-tracker-app:
    container_name: expense_tracker
    image: ${DOCKER_HUB_CREDS_USR}/expense-tracker:latest
    build: .
    ports:
    - target: 5000
      published: 5000
    environment:
      DATABASE_URI: mysql+pymysql://root:password@db:3306/sqlalchemy
    depends_on:
      - mysql
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: db