version: "3.8"
services:
  expense-tracker-app:
    container_name: expense_tracker
    image: ${DOCKER_HUB_CREDS_USR}/expense-tracker:latest
    build: .
    ports:
    - target: 5000
      published: 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
    depends_on:
      - database
  database:
    container_name: expense_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: expense
    volumes:
      - type: volume
        source: expense_database_volume
        target: /var/lib/mysql
volumes:
  todo_database_volume: 